defaults:
  - defaults
  - training/vcreg: convnext_tv
  - training/approach: finetuning
  - training/optimizer: adam
  - override hydra/launcher: slurm
  - _self_


hydra:
  searchpath:
    - file://src/config
  mode: MULTIRUN
  launcher:
    timeout_min: 240
  sweep:
    dir: results/2024/${now:%m.%d}/${now:%H-%M-%S}
  sweeper:
    params:
      training.vcreg.reg_layers: classifier$, .*after_skipping


misc:
  results_path: ${hydra:sweep.dir}/${hydra:sweep.subdir}

data:
  num_workers: 16
model:
  network: convnext_tiny
training:
  lr: 1e-3



