defaults:
  - defaults
  - debug
  - training/approach: lwf
  - networks: resnet
  - _self_

training:
  vcreg:
    scale: false
    reg_layers: .*after_relu
    smooth_cov: 1.0
    var_weight: 0.1
    cov_weight: 0.1
    n_first_task: -1

