defaults:
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

data:
  datasets:
    - cifar100_fixed
  num_workers: 4
  batch_size: 128
  num_tasks: 4
  nc_first_task: null
  ne_first_task: null
  nc_per_task: null
  use_valid_only: false
  use_test_as_val: false
  stop_at_task: 0
  max_classes_per_dataset: null
  max_examples_per_class_trn: null
  max_examples_per_class_val: null
  max_examples_per_class_tst: null
  extra_aug: ""
  exemplars:
    num_exemplars: 0
    exemplar_selection: random
misc:
  gpu: 0
  results_path: "results"
  exp_name: null
  tags: null
  seed: 0
  log:
    - disk
    - wandb
  save_models: false
  cache_first_task_model: false
  last_layer_analysis: false
  no_cudnn_deterministic: false
  cm: false
model:
  network: resnet34_skips
  keep_existing_head: false
  pretrained: false
training:
  vcreg: null
  nepochs: 100
  lr: 0.1
  scheduler_milestones: [30, 60, 80]
  early_stopping:
    lr_min: 1e-4
    lr_factor: 3
    lr_patience: 5
  clipping: 100.0
  momentum: 0.0
  weight_decay: 0.0
  multi_softmax: false
  fix_bn: false
  eval_on_train: true
  gridsearch_tasks: 0
  warmup:
    wu_nepochs: 0
    wu_lr: 0.1
    wu_fix_bn: true
    wu_scheduler: constant
    wu_patience: null
    wu_wd: 0.001
