defaults:
  - defaults
  - training/vcreg: null
  - training/approach: finetuning
  - training/optimizer: adam
  - override hydra/launcher: slurm
  - _self_


hydra:
  searchpath:
    - file://src/config
  mode: MULTIRUN
  launcher:
    timeout_min: 240
  sweep:
    dir: results/2024/${now:%m.%d}/${now:%H-%M-%S}
  sweeper:
      params:
        data.exemplars.num_exemplars: 0, 2_000


misc:
  results_path: ${hydra:sweep.dir}/${hydra:sweep.subdir}
  save_models: true
  exp_name: final_checkpoint

data:
  num_workers: 16

training:
  lr: 1e-3

model:
  network: convnext_tiny


